version: '3'
services:
    mariadb:
        image: mariadb/server:10.3
        container_name: mariadb-server
        environment:
          - MYSQL_ROOT_PASSWORD=root
        ports:
            - 3306:3306
        volumes:
          - /home/muhdfayyaz/development/databases/mysql/data/mariadb:/var/lib/mysql     
        networks:
          webnet:
            ipv4_address: 172.18.0.4


networks:
    webnet:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/24
